# Generated by Django 3.1.7 on 2021-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PublicKey', models.CharField(max_length=160)),
                ('LastSeen', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToClient', models.IntegerField()),
                ('FromClient', models.IntegerField()),
                ('Type', models.CharField(max_length=1)),
                ('Blob', models.CharField(max_length=1000)),
            ],
        ),
    ]
